### PR TITLE
basic source code tidy up, step() -> step6502()

### PR DESCRIPTION
**Pull request by john-walsh**
Only code change is renaming the function step() -> step6502(), to be inline with the other user functions.

Updated comments / header / documentation, and move it around a bit.

Moved function reset6502() to be with the other 'user' functions.

Put usual wrappers around the header file.

### CODE REVIEW

**Comment by omarandlorraine** [comment]
Thanks so much for your contribution. There's some good stuff in here.

But I've got some remarks:

- **rename step function** that's good
- **Updated comments / header / documentation, and move it around a bit.** that's as it should be. Can you find out if we can get this to render as Markdown? If so, we'll automate the process of having Github maintain a `DOCUMENTATION.md` file or some such.
- **Put usual wrappers around the header file.** one question: the interface here is absolutely not idiomatic C++. does anything need to be done about that, or would you expect the end user to implement a wrapper class?
- There's a typo in the documentation, "folk" for "fork".
- Also do you know why `make test` is failing? Looks like some symbols are being defined more than once.

**Comment by omarandlorraine** [comment]
This pull request will close issue #12 on merge.

**Comment by john-walsh** [comment]
- **build fail** - ah, I hadn't built the code with the 'test.c'. I had made a change to the defines for choosing the CPU type, and it was causing the compile error - fixed.

step6502() - updated in tests.c

- **folk typo** - fixed.

- **Updated comments / header / documentation** - that is in markdown format.

Would you rather have a separate file for the documentation?

I think that may be better, and I wanted to add a little more detail too.

**Comment by john-walsh** [comment]
- **header wrappers** - that just allows the code to be built in a C++ environment, and the compiler will recognise the code as such (for linking, etc...). We don't need to do anything more, it will be up to the host project to call the code, as normal.

**Comment by omarandlorraine** [comment]
I think a separate file makes sense for the changelog.

But I really like your idea of documenting the functions properly as well. Doxygen-style documentation is perfect for this kind of thing.

**Comment by john-walsh** [comment]
Do you want to merge the changes so far, and then we can make the new documentation?

**Comment by omarandlorraine** [comment]
Good idea. Thanks for the contribution!

**Pull request merged**
