### PR TITLE
more changes to aid the use as a library, and some documentation chan…

### PR DESCRIPTION
**Pull request by john-walsh**
more changes to aid the use as a library, and some documentation changes (CHANGELOG.md)

### CODE REVIEW

**Comment by omarandlorraine** [comment]
What is the purpose of splitting apart `context_6502_cpu` and `context_6502_emu`? I feel like the members of those structs could just as well be members of `context_6502`. But it's possible I'm missing something

**Comment by omarandlorraine** [comment]
Let's not use this kind of megaphone announcement:

```
/*********************************************************************
DEFINE's
*********************************************************************/
```

and similar VERY LOUD TITLES all over the codebase. We don't need to announce that the `#define`s follow, it's obvious to anyone who can read C. So they have an adverse effect on the noise-to-signal ratio.

**Comment by john-walsh** [comment]
> What is the purpose of splitting apart `context_6502_cpu` and `context_6502_emu`?

It gives the ability to 'save/restore' the state of each element, independently.

I know that's not used/needed now, but it could be (and I may need it in my host code).

So it's more about being of good design, rather than anything practical right now.

**Comment by john-walsh** [comment]
> Let's not use this kind of megaphone announcement:

So this is a style/preference type of thing, and there will be many different opinions.

For me, it gives a better structure/layout to the source code. And as a part of what I would consider the documentation side of things, I'd prefer to do more, rather than a minimalist approach. I think it helps the readability of the source.

Other examples:

[rosterloh/template.c](https://gist.github.com/rosterloh/8375961)

[C Coding Standards](http://emboss.open-bio.org/html/dev/apcs02.html)

So I'd ask you to consider this, but it is your project, so I'll go with what you decide.

I am going away for a couple of days, so take your time, and don't worry if I don't reply until I'm back.

ps. there is the similar debate over the layout style of opening braces - same line or line below, and indentation... I prefer this:

```
if (a)
{
  do stuff;
}

```
But again, it's not my code and I don't want to push my wishes on it too much.

**Comment by john-walsh** [comment]
OK, I'm back.

Let me know what you want to do with the comments - keep, reduce, ...?

**Comment by omarandlorraine** [comment]
My first preference would be to remove them altogether.

But if your style guide prescribes a column width I'll suggest an alternative:

```
/********* defines ****/
```

a single line that's 80 columns, say, and lower case. Not as screamy.

**Comment by john-walsh** [comment]
I'm quite happy to make them 'smaller'.

I would use 70 column.

I'll do an update.

**Comment by john-walsh** [comment]
How about something like the style of NASA?

[NASA coding standard](https://ntrs.nasa.gov/api/citations/20080039927/downloads/20080039927.pdf)

**Comment by omarandlorraine** [comment]
> How about something like the style of NASA

How are you going to enforce it going forwards?

**Comment by john-walsh** [comment]
I'm not sure it needs that. I'm not trying to have rules for every little detail.

We can write a short guide, but it's more just that the code is neat and readable.

I don't see this code growing to be so big that it needs so much of a guide.

**Comment by omarandlorraine** [comment]
We agree. We don't need a style guide. So is this ready to merge?

**Comment by john-walsh** [comment]
I'll update the files tomorrow.

**Comment by john-walsh** [comment]
I just updated the header file - see what you think:

[fake6502.h](https://github.com/john-walsh/fake6502/blob/master/fake6502.h)

**Comment by omarandlorraine** [comment]
Yeah that's better 🙂

Is there any more to include in the pull request or shall I merge it in?

**Comment by john-walsh** [comment]
I put the other files in, so check on that and then it's ready to merge, if OK.

Then it will be on to my third (and I think) last set of updates.

**Comment by omarandlorraine** [comment]
Thanks for the contribution John Walsh

**Pull request merged**
